apiVersion: v1
kind: Pod
metadata:
 name: mypod
 namespace: roboshop
spec:
 containers:
  - image: nginx:latest
    name: myimage
    ports:
    - containerPort: 80

# kubectl create -f pod.yaml
# kubectl get pods -n roboshop -o wide
# kubectl get pods -A
# kubectl delete pod podname