---
apiVersion: v1
kind: Pod
metadata:
 name: mypod
 labels:
  tier: frontend
spec:
 containers:
  -image: nginx
   imagePullPolicy: Always
   name: myimage
   ports:
   - containerPort: 80 
---
apiVersion: v1
kind: Service
metadata:
 name: web
spec:
 selector:
  tier: frontend
 ports:
  - protocol: TCP
    port: 80 # serviceport
    targetPort: 80