
apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::608782704145:role/eksctl-myekscluster01-nodegroup-n-NodeInstanceRole-5LSCVG6X08P0
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::608782704145:user/roboshopuser
      username: roboshopuser
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn: arn:aws:iam::608782704145:role/eksctl-myekscluster01-nodegroup-n-NodeInstanceRole-5LSCVG6X08P0\n  username: system:node:{{EC2PrivateDNSName}}\n","mapUsers":"arn:aws:iam::608782704145:user/roboshopuser\nusername: roboshopuser\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2023-04-07T07:04:03Z","name":"aws-auth","namespace":"kube-system","resourceVersion":"1479","uid":"af19499d-1c18-459e-8469-0204636f1104"}}
  creationTimestamp: "2023-04-07T07:04:03Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "5279"
  uid: af19499d-1c18-459e-8469-0204636f1104
