---
apiVersion: v1
kind: Namespace
metadata:
 name: roboshop
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: roboshop
  name: roboshop-reader
rules:
- apiGroups: ["*"] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["watch","get","list", "delete"]
- apiGroups: ["*"] # "" indicates the core API group
  resources: ["deployments"]
  verbs: ["create" , "get", "list", "delete"]


# create role
# rolebinding
# add user in aws-auth -n kubesystem 
# kubectl get configmap aws-auth -n kube-system -o yaml
# aws eks update-kubeconfig --region us-east-1 --name clustername