apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: roboshop-reader-rolebinding
  namespace: roboshop
subjects:
- kind: User
  name: roboshopuser
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role 
  name: roboshop-reader
  apiGroup: rbac.authorization.k8s.io