apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: manual
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-ebs-volume
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-0b580a797aa2271c1
    fsType: ext4
---
apiVersion: v1
kind: persistentVolumeClaim
metadata:
 name: my-ebs-pvc
spec:
 storageClassName: manual
 accessModes:
 - ReadWriteOnce
 resources:
  requests:
   storage: 10Gi
 volumeName: my-ebs-volume
---
apiversion: v1
kind: Pod
metadata:
 name: my-pod
spec:
 containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - name: my-ebs-volume
      mountPath: /usr/share/nginx
 volumes:
 - name: my-ebs-volume
   persistentVolumeClaim:
   - claimName: my-ebs-pvc    