---
apiVersion: v1
kind: PersistentVolume
metadata:
 name: pv-vol1
spec:
 persistentVolumeReclaimPolicy: Retain # Types: Retain,Delete, Recycle
 accessModes:
  - ReadWriteOnce
 capacity:
  storage: 10Gi
 awsElasticBlockStore:
  volumeID:
  fsType:
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: myclaim
spec:
 accessModes:
  - ReadWriteOnce
 resources:
  requests:
   storage: 10Gi
---
# using PVCs in Pods
apiVersion: v1
kind: Pod
metadata:
 name: mypod
spec:
 containers:
  - image: nginx
    name: myimage
    volumeMounts:
     name: myvolumes
     mountPath: /var/www/html
 volumes:
 - name: myvolumes
   PersistentVolumeClaim:
    claimName: myclaim
