apiVersion: apps/v1
kind: Deployment
metadata:
 name: mydeployment
 labels:
  name: frontend
spec:
 replicas: 20
 strategy:
  type: RollingUpdate
  rollingUpdate:
   maxUnavailable: 2 # we asked for 10, we are okay if 9 are running at the time of upgrade
   maxSurge: 2 # we asked for 10, we are okay at the time of upgrade 11 are running
 selector:
  matchLabels:
   name: frontend
 template:
  metadata:
   labels:
    name: frontend
  spec:
   containers:
    - image: nginx
      name: myimage
      ports:
      - containerPort: 80
