apiVersion: apps/v1
kind: Deployment
metadata:
 name: mydeployment
 annotations:
  deployment.kubernetes.io/change-cause: "upgraded to version 2.0"
 labels:
  name: frontend
spec:
 replicas: 10
 strategy:
  type: RollingUpdate
  rollingUpdate:
   maxUnavailable: 2 # we asked for 10, we are okay if 9 are running at the time of upgrade
   maxSurge: 2 # we asked for 10, we are okay at the time of upgrade 11 are running
 selector:
  matchLabels:
   name: frontend
 template:
  metadata:
   labels:
    name: frontend
  spec:
   containers:
    - image: nginx
      name: myimage
      command: ["sleep" , "100000"]
      ports:
      - containerPort: 80

# kubectl rollout status deployment/deployment_name
# kubectl rollout undo deployment/deployment_name
# kubectl rollout history deployment/deployment_name
