apiVersion: apps/v1
kind: Deployment
metadata:
 name: mydeployment
 labels:
  name: mydep
  tier: frontendUI
spec:
 replicas: 20
 selector:
  matchLabels:
   tier: frontendUI
 template:
  metadata:
   labels:
    tier: frontendUI
  spec:
   containers:
    - image: nginx
      name: myimage
  