apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: myreplicaset # replicaset name
 labels: # these are labels related to replica set resource
  app: nginx
  tier: frontend
spec:
  # modify replicas according to your case
 replicas: 15
 selector:
  matchLabels: # this is the syntax replica set uses to find which pod should be scaled and maintained
   
   tier: frontend

 template: # pod template, labels are related to pod
  metadata:
   labels:
    tier: frontend1
  spec:
   containers:
   - image: nginx
     name: myimage