# apiVersion: eksctl.io/v1alpha5
# kind: ClusterConfig

# metadata:
#   name: spot-cluster
#   region: ap-south-1

# managedNodeGroups:

# # `instanceTypes` defaults to [`m5.large`] and two instances
# - name: spot-1
#   spot: true
#   ssh:
#     publicKeyName: my-ec2-keypair
# eksctl create cluster --config-file=eks-cluster.yaml
# eksctl delete cluster --config-file=eks-cluster.yaml
# 'eksctl delete cluster --region=us-east-1 --name=myekscluster01' 

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
 name: myekscluster02
 region: us-east-1

managedNodeGroups:
 - name: nodegroup
   instanceType: t3.medium
   spot: true
   minSize: 2
   maxSize: 2
   desiredCapacity: 2
   ssh:
    publicKeyName: testkey


