apiVersion: v1
kind: Pod
metadata:
 name: multiple
 namespace: roboshop
spec:
 containers:
  - image: nginx
    name: mynginximage
    ports:
    - containerPort: 80
  - image: almalinux
    name: sidecar
    command: ["sleep" , "200"]